wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714191297.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
